apiVersion: v1
kind: Service
metadata:
  name: {{ include "openl-webstudio.fullname" . }}
  labels:
    {{- include "openl-webstudio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: 30090
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "openl-webstudio.selectorLabels" . | nindent 4 }}
